### ISSUE TITLE
Mapa Mental "Conjuntos"

### ISSUE THREAD

**Issue by Eddi3mendoz** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Eddi3mendoz#2]
[24620220-Conjuntos.pdf](https://github.com/user-attachments/files/17101596/24620220-Conjuntos.pdf)

**Comment by BautistaLizbeth** [comment]
Manejo conceptual y dominio del tema: 5/5
Relación entre los conceptos incluidos en el mapa: 5/5
Calidad de la presentación: 5/5
Jerarquía: 5/5
CALIFICACIÓN: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
